name: find all issues

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master

jobs:
  print-issues:
    name: print_issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#      - name: "Find issues"
#        id: issues
#        uses: actions-cool/issues-helper@v3
#        with:
#          actions: 'find-issues'
#          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: octokit/request-action@v2.x
        id: alerts
        with:
          route: GET /repos/{repo}/dependabot/alerts?state=open&severity=critical
          repo: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
      - run: |
          echo "The current response is: ${{ steps.alerts.outputs.data }}"
      - uses: actions/github-script@v6
        with:
          script: |
            // if PR is labeled as dependencies, skip 
            const issues = ${{ steps.alerts.outputs.data }}
            console.log({length: issues.length});
            let message = "";
            let failed = false;
            if (issues.length == 0) {
              message = `Your repository has no critical alert :tada:`;
            } else {
              message = `Your repository has ${issues.length} critical alerts! please address those first.
              failed = true;
            }
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
            
            // exit with an error code if failed is true

