name: find all issues

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master

jobs:
  print-issues:
    name: print_issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#      - name: "Find issues"
#        id: issues
#        uses: actions-cool/issues-helper@v3
#        with:
#          actions: 'find-issues'
#          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: octokit/request-action@v2.x
        id: alerts
        with:
          route: GET /repos/{repo}/dependabot/alerts
          repo: ${{ github.repository}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo "The current response is: ${{ steps.alerts.outputs.data }}"
      
