name: Only run on push into the main branch

on:
  push:
    branches:
      - main

jobs:
  say-hi:
    name: say_hi
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - run: | 
        ls
        echo hi
        
    
